---
steps:
- name: gcr.io/leszek-jinx-main/terravet.img
  dir: deployments/app1/dev
  args:
  - terraform 
  - init
- name: gcr.io/leszek-jinx-main/terravet.img
  dir: deployments/app1/dev
  entrypoint: terraform
  args:
  - plan 
  - -out=terraform.plan
- name: gcr.io/leszek-jinx-main/terravet.img
  entrypoint: "/bin/bash"
  args: ['-c', 'terraform show -json terraform.plan > terraform.json']
  dir: deployments/app1/dev
- name: google/cloud-sdk:latest
  dir: deployments/app1/dev
  args:
  - gcloud
  - beta
  - terraform
  - vet
  - terraform.json
  - --policy-path=../../../policy-library/
  - --project
  - "leszek-jinx-main"
